class BibliotecaError(Exception):
    """Base de todas las excepciones del dominio."""

class LibroNoEncontrado(BibliotecaError): ...
class UsuarioNoEncontrado(BibliotecaError): ...
class PrestamoNoEncontrado(BibliotecaError): ...
class StockInsuficiente(BibliotecaError): ...
class LimitePrestamosAlcanzado(BibliotecaError): ...
class UsuarioInactivo(BibliotecaError): ...
class EmailYaRegistrado(BibliotecaError): ...
class PrestamoYaDevuelto(BibliotecaError): ...
